std_msgs/Header header
bool arrive
string stop_reason
float64 time_spent

float64 global_path_length
float64 traveled_path_length
float64 total_rotation_rad
float64 smoothness_index

float64 min_distance_to_obstacle
float64 distance_to_goal
float64 yaw_difference_to_goal

float64 avg_control_frequency  # /bubble_path
float64 avg_cmd_vel_frequency  # /input/nav_cmd_vel

float64 avg_memory1_usage
float64 avg_memory2_usage
float64 avg_memory3_usage
float64 avg_memory4_usage
float64 avg_cpu1_usage
float64 avg_cpu2_usage
float64 avg_cpu3_usage
float64 avg_cpu4_usage