#!/usr/bin/python3
"""
DWA Keyboard Trigger - press SPACE to start DWA after AIT* path planning.
Run in a separate terminal: ros2 run aitstar_path_planner dwa_keyboard_trigger
"""
import sys
import tty
import termios
import select
import rclpy
from rclpy.node import Node
from std_msgs.msg import Bool


class DwaKeyboardTrigger(Node):
    def __init__(self):
        super().__init__('dwa_keyboard_trigger')
        self.pub = self.create_publisher(Bool, '/start_dwa', 10)
        self.get_logger().info('DWA 鍵盤觸發節點已啟動')
        self.get_logger().info('等待 AIT* 規劃完成後，按 [空白鍵] 啟動導航')
        self.get_logger().info('按 [Ctrl+C] 退出')


def main(args=None):
    rclpy.init(args=args)
    node = DwaKeyboardTrigger()

    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)

    try:
        while rclpy.ok():
            rclpy.spin_once(node, timeout_sec=0.05)
            tty.setraw(fd)
            rlist, _, _ = select.select([sys.stdin], [], [], 0.05)
            termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
            if rlist:
                key = sys.stdin.read(1)
                if key == ' ':
                    msg = Bool()
                    msg.data = True
                    node.pub.publish(msg)
                    node.get_logger().info('>>> 已發送啟動指令! <<<')
                elif key == '\x03':
                    break
    except KeyboardInterrupt:
        pass
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
