uint8 LOCOLIZAR_2D_VLP16_ODOM=0
uint8 LOCOLIZAR_2D_HOKUYO_ODOM=1
uint8 LOCOLIZAR_2D_YD_ODOM=2
uint8 LOCOLIZAR_2D_YD_SCAN_MATCHING=3
uint8 LOCOLIZAR_3D_VLP16_ODOM=4

uint8 localizer
string map_file
---
int16 pid